@ToDoApi_HostAddress = http://localhost:5251

POST {{ToDoApi_HostAddress}}/todos
Accept: application/json
Content-Type: application/json

{
  "description": ""
}

###

POST {{ToDoApi_HostAddress}}/todos/6613de28-82ba-4291-bd69-3e422b5cbd8c/complete
Accept: application/json
Content-Type: application/json

###

GET {{ToDoApi_HostAddress}}/todos
Accept: application/json